const IMG = {
  hundru: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&q=80',
  netarhat: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  patratu: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
  deoghar: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
  betla: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
  dassam: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800&q=80',
  jonha: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
  tagore: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80',
  rock: 'https://images.unsplash.com/photo-1513836279014-a89f7a76c86f?w=800&q=80',
  tribal: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
  stadium: 'https://images.unsplash.com/photo-1459865260367-59721e017ef0?w=800&q=80',
  ranchi: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80',
  jamshedpur: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&q=80',
  waterfall: 'https://images.unsplash.com/photo-1519904981064-b0cf111d2940?w=800&q=80',
  forest: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
  hills: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  temple: 'https://images.unsplash.com/photo-1580618672591-eb180a1ea49b?w=800&q=80',
  adventure: 'https://images.unsplash.com/photo-1551632811-561732d0560b?w=800&q=80',
};

const districts = [
  { name: 'Ranchi', image: IMG.ranchi, description: 'Capital city with waterfalls, hills & sports heritage', touristPlaces: 45, culturalPlaces: 20, hiddenGems: 12 },
  { name: 'Deoghar', image: IMG.deoghar, description: 'Spiritual hub with Baidyanath Temple', touristPlaces: 30, culturalPlaces: 25, hiddenGems: 8 },
  { name: 'Palamu', image: IMG.betla, description: 'Home to Betla National Park & wildlife', touristPlaces: 22, culturalPlaces: 10, hiddenGems: 15 },
  { name: 'Dumka', image: IMG.tribal, description: 'Tribal heartland with rich Santhal culture', touristPlaces: 18, culturalPlaces: 22, hiddenGems: 10 },
  { name: 'Bokaro', image: IMG.hills, description: 'Industrial city with scenic dams & parks', touristPlaces: 15, culturalPlaces: 8, hiddenGems: 6 },
  { name: 'Dhanbad', image: IMG.ranchi, description: 'Coal capital with heritage & nature spots', touristPlaces: 12, culturalPlaces: 10, hiddenGems: 5 },
  { name: 'Jamshedpur', image: IMG.jamshedpur, description: 'Steel city built by Tata — industrial tourism', touristPlaces: 25, culturalPlaces: 18, hiddenGems: 9 },
  { name: 'West Singhbhum', image: IMG.waterfall, description: 'Land of waterfalls and tribal villages', touristPlaces: 20, culturalPlaces: 15, hiddenGems: 18 },
  { name: 'Latehar', image: IMG.netarhat, description: 'Gateway to Netarhat — Queen of Chotanagpur', touristPlaces: 16, culturalPlaces: 8, hiddenGems: 12 },
  { name: 'Giridih', image: IMG.hills, description: 'Hill station with Parasnath pilgrimage', touristPlaces: 14, culturalPlaces: 12, hiddenGems: 7 },
];

const places = [
  {
    name: 'Hundru Falls',
    district: 'Ranchi',
    category: 'Waterfalls',
    description: 'One of the highest waterfalls in Jharkhand, plunging 98 meters into the Subarnarekha river gorge.',
    images: [IMG.hundru],
    coordinates: { lat: 23.396, lng: 85.378 },
    bestTime: 'July - February',
    nearbyPlaces: [
      { name: 'Dassam Falls', distance: '18 km' },
      { name: 'Jonha Falls', distance: '22 km' },
      { name: 'Tagore Hill', distance: '28 km' },
    ],
    rating: 4.8,
    reviewCount: 124,
  },
  {
    name: 'Netarhat',
    district: 'Latehar',
    category: 'Hills & Valleys',
    description: 'The Queen of Chotanagpur — breathtaking sunrise views and pine forests.',
    images: [IMG.netarhat],
    coordinates: { lat: 23.483, lng: 84.267 },
    bestTime: 'October - March',
    nearbyPlaces: [
      { name: 'Koel View Point', distance: '5 km' },
      { name: 'Magnolia Sunset Point', distance: '8 km' },
    ],
    rating: 4.9,
    reviewCount: 98,
  },
  {
    name: 'Patratu Valley',
    district: 'Ranchi',
    category: 'Hills & Valleys',
    description: 'Scenic winding roads through lush green valleys — a photographer\'s paradise.',
    images: [IMG.patratu],
    coordinates: { lat: 23.633, lng: 85.317 },
    bestTime: 'October - June',
    nearbyPlaces: [
      { name: 'Patratu Dam', distance: '3 km' },
      { name: 'Ramgarh Hills', distance: '15 km' },
    ],
    rating: 4.7,
    reviewCount: 156,
  },
  {
    name: 'Baidyanath Temple',
    district: 'Deoghar',
    category: 'Temples',
    description: 'One of the twelve Jyotirlingas — a major pilgrimage destination.',
    images: [IMG.deoghar],
    coordinates: { lat: 24.482, lng: 86.695 },
    bestTime: 'Shravan month (July-August)',
    nearbyPlaces: [
      { name: 'Basukinath Temple', distance: '42 km' },
      { name: 'Naulakha Mandir', distance: '2 km' },
    ],
    rating: 4.9,
    reviewCount: 210,
  },
  {
    name: 'Betla National Park',
    district: 'Palamu',
    category: 'Forests & Wildlife',
    description: 'Premier wildlife sanctuary with tigers, elephants, and rich biodiversity.',
    images: [IMG.betla],
    coordinates: { lat: 23.917, lng: 84.183 },
    bestTime: 'November - April',
    nearbyPlaces: [
      { name: 'Palamu Fort', distance: '25 km' },
      { name: 'Lodh Falls', distance: '40 km' },
    ],
    rating: 4.6,
    reviewCount: 87,
  },
  {
    name: 'Dassam Falls',
    district: 'Ranchi',
    category: 'Waterfalls',
    description: 'A spectacular 44-meter waterfall on the Kanchi river.',
    images: [IMG.dassam],
    coordinates: { lat: 23.417, lng: 85.433 },
    bestTime: 'July - January',
    nearbyPlaces: [
      { name: 'Hundru Falls', distance: '18 km' },
      { name: 'Jonha Falls', distance: '12 km' },
    ],
    rating: 4.5,
    reviewCount: 76,
  },
  {
    name: 'Jonha Falls',
    district: 'Ranchi',
    category: 'Waterfalls',
    description: 'Also known as Gautamdhara — a serene waterfall with a Buddhist temple nearby.',
    images: [IMG.jonha],
    coordinates: { lat: 23.383, lng: 85.583 },
    bestTime: 'July - February',
    nearbyPlaces: [
      { name: 'Dassam Falls', distance: '12 km' },
      { name: 'Hundru Falls', distance: '22 km' },
    ],
    rating: 4.4,
    reviewCount: 65,
  },
  {
    name: 'Tagore Hill',
    district: 'Ranchi',
    category: 'Hills & Valleys',
    description: 'Historic hill associated with Rabindranath Tagore\'s elder brother.',
    images: [IMG.tagore],
    coordinates: { lat: 23.383, lng: 85.317 },
    bestTime: 'October - March',
    nearbyPlaces: [
      { name: 'Rock Garden', distance: '4 km' },
      { name: 'Hundru Falls', distance: '28 km' },
    ],
    rating: 4.3,
    reviewCount: 54,
  },
  {
    name: 'Rock Garden',
    district: 'Ranchi',
    category: 'Adventure Trails',
    description: 'Man-made garden with rock sculptures and scenic Kanke Dam views.',
    images: [IMG.rock],
    coordinates: { lat: 23.400, lng: 85.333 },
    bestTime: 'Year round',
    nearbyPlaces: [
      { name: 'Tagore Hill', distance: '4 km' },
      { name: 'Kanke Dam', distance: '1 km' },
    ],
    rating: 4.2,
    reviewCount: 48,
  },
  {
    name: 'Ranchi Cricket Stadium',
    district: 'Ranchi',
    category: 'Sports',
    description: 'Home ground of MS Dhoni — JSCA International Stadium Complex.',
    images: [IMG.stadium],
    coordinates: { lat: 23.317, lng: 85.283 },
    bestTime: 'During cricket season',
    nearbyPlaces: [
      { name: 'Dhoni Legacy Trail', distance: '5 km' },
      { name: 'Hundru Falls', distance: '25 km' },
    ],
    rating: 4.8,
    reviewCount: 189,
  },
  {
    name: 'Lupung Waterfall',
    district: 'West Singhbhum',
    category: 'Waterfalls',
    description: 'A hidden gem discovered by local explorers — pristine and untouched.',
    images: [IMG.waterfall],
    hiddenGem: true,
    explorerName: 'Ravi Explorer',
    coordinates: { lat: 22.483, lng: 85.083 },
    bestTime: 'July - December',
    rating: 4.9,
    reviewCount: 12,
  },
  {
    name: 'Secret Sunset Point',
    district: 'Latehar',
    category: 'Hills & Valleys',
    description: 'Offbeat viewpoint with 360° sunset panoramas over Chotanagpur plateau.',
    images: [IMG.netarhat],
    hiddenGem: true,
    explorerName: 'Priya Travels',
    coordinates: { lat: 23.500, lng: 84.300 },
    bestTime: 'October - March',
    rating: 4.8,
    reviewCount: 8,
  },
  {
    name: 'Tati Jharna',
    district: 'Dumka',
    category: 'Waterfalls',
    description: 'Sacred waterfall in Santhal tribal territory with cultural significance.',
    images: [IMG.waterfall],
    hiddenGem: true,
    explorerName: 'Santhal Stories',
    coordinates: { lat: 24.267, lng: 87.250 },
    bestTime: 'August - January',
    rating: 4.7,
    reviewCount: 15,
  },
  {
    name: 'Tribal Village Experience',
    district: 'Dumka',
    category: 'Tribal Culture',
    description: 'Immersive homestay with Santhal tribe — dance, cuisine & crafts.',
    images: [IMG.tribal],
    hiddenGem: true,
    explorerName: 'Culture Connect',
    coordinates: { lat: 24.267, lng: 87.250 },
    bestTime: 'November - February',
    rating: 4.9,
    reviewCount: 22,
  },
  {
    name: 'Jubilee Park',
    district: 'Jamshedpur',
    category: 'Heritage',
    description: 'Tata-built park celebrating Jamshedpur\'s golden jubilee — industrial heritage tourism.',
    images: [IMG.jamshedpur],
    coordinates: { lat: 22.800, lng: 86.183 },
    bestTime: 'Year round',
    nearbyPlaces: [
      { name: 'Tata Steel Plant', distance: '5 km' },
      { name: 'Dimna Lake', distance: '12 km' },
    ],
    rating: 4.4,
    reviewCount: 67,
  },
];

const reels = [
  {
    title: 'Hundru Falls Adventure',
    thumbnail: IMG.hundru,
    instagramLink: 'https://www.instagram.com/reel/example1/',
    placeName: 'Hundru Falls',
    location: 'Ranchi, Jharkhand',
  },
  {
    title: 'Netarhat Sunrise',
    thumbnail: IMG.netarhat,
    instagramLink: 'https://www.instagram.com/reel/example2/',
    placeName: 'Netarhat',
    location: 'Latehar, Jharkhand',
  },
  {
    title: 'Patratu Valley Drive',
    thumbnail: IMG.patratu,
    instagramLink: 'https://www.instagram.com/reel/example3/',
    placeName: 'Patratu Valley',
    location: 'Ranchi, Jharkhand',
  },
  {
    title: 'Tribal Dance Festival',
    thumbnail: IMG.tribal,
    instagramLink: 'https://www.instagram.com/reel/example4/',
    placeName: 'Dumka',
    location: 'Dumka, Jharkhand',
  },
  {
    title: 'Betla Safari',
    thumbnail: IMG.betla,
    instagramLink: 'https://www.instagram.com/reel/example5/',
    placeName: 'Betla National Park',
    location: 'Palamu, Jharkhand',
  },
  {
    title: 'Deoghar Temple Visit',
    thumbnail: IMG.deoghar,
    instagramLink: 'https://www.instagram.com/reel/example6/',
    placeName: 'Baidyanath Temple',
    location: 'Deoghar, Jharkhand',
  },
];

const users = [
  { name: 'Admin User', email: 'admin@jharyatra.ai', password: 'admin123', role: 'admin' },
  { name: 'Ravi Explorer', email: 'explorer@jharyatra.ai', password: 'explorer123', role: 'explorer', explorerVerified: true, instagram: '@explorejharkhand' },
  { name: 'Priya Travels', email: 'priya@jharyatra.ai', password: 'explorer123', role: 'explorer', explorerVerified: true, instagram: '@travelwithravi' },
  { name: 'Tourist Demo', email: 'tourist@jharyatra.ai', password: 'tourist123', role: 'tourist' },
];

module.exports = { districts, places, reels, users, IMG };
